<a href="https://colab.research.google.com/github/aqibstar/30-days-of-code-python/blob/main/Pandas_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
marks= pd.Series([30,22,88,22])
print(marks)

0    30
1    22
2    88
3    22
dtype: int64

In [ ]:
marks1 = pd.Series([30,22,88,22],
index=['a','b','c','d'])
print(marks1)

a    30
b    22
c    88
d    22
dtype: int64

In [ ]:
data={
    "Name": ["aqib","amit","priya"],
    "Age" : [22,23,24],
    "Marks":[45,66,78]
}
df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0   aqib   22     45
1   amit   23     66
2  priya   24     78

In [ ]:
df.index
pd.RangeIndex(start=0, stop=3,step=1)
df

    Name  Age  Marks
0   aqib   22     45
1   amit   23     66
2  priya   24     78

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
df["Name"]

0     aqib
1     amit
2    priya
Name: Name, dtype: object

In [ ]:
df[["Name","Age"]]

    Name  Age
0   aqib   22
1   amit   23
2  priya   24

In [ ]:
df["Passed"] = df["Marks"] >=70

In [ ]:
df

    Name  Age  Marks  Passed
0   aqib   22     45   False
1   amit   23     66   False
2  priya   24     78    True

In [ ]:
df["Bonnus"] = df["Passed"] <=70
df

    Name  Age  Marks  Passed  Bonnus
0   aqib   22     45   False    True
1   amit   23     66   False    True
2  priya   24     78    True    True

In [ ]:
df["Marks"] = df["Marks"] + df["Bonnus"]
df

    Name  Age  Marks  Passed  Bonnus
0   aqib   22     46   False    True
1   amit   23     67   False    True
2  priya   24     79    True    True

In [ ]:
df.drop("Age" , axis=1, inplace=True)

In [ ]:
df

    Name  Marks  Passed
1   amit     67   False
2  priya     79    True

In [ ]:
df.drop(0, axis=0, inplace=True)

In [ ]:
df

    Name  Marks  Passed  Bonnus
1   amit     67   False    True
2  priya     79    True    True

In [ ]:
df.iloc[1]

Name      priya
Marks        79
Passed     True
Bonnus     True
Name: 2, dtype: object

In [ ]:
df.iloc[0:2]

    Name  Marks  Passed  Bonnus
1   amit     67   False    True
2  priya     79    True    True

In [ ]:
df.iloc[0:1]

   Name  Marks  Passed  Bonnus
1  amit     67   False    True

In [ ]:
df.loc[1,"Name"]

'amit'

In [ ]:
df.loc[0:2, ["Name","Marks"]]

    Name  Marks
1   amit     67
2  priya     79